-- ============================================================
-- ARCHIVED — DO NOT RUN
-- ============================================================
-- These tables were originally drafted for a standalone resources
-- app database. They now all exist on the WriFe Platform Supabase
-- project (gzmgjkbtsvezfclmreru), which is the single source of truth.
--
-- Tables already present on the platform:
--   profiles, schools, subscriptions, classes, class_members
--   ai_sessions, ai_attempts, daily_streaks, usage_quotas, ai_tool_assignments
--
-- To add new tables for resources.wrife.co.uk, create a new
-- numbered migration (004_...) with only the net-new schema.
-- ============================================================
