-- ============================================================
-- ARCHIVED — DO NOT RUN
-- ============================================================
-- RLS policies for the tables in 001_init.sql.
-- Since 001_init.sql is archived (all tables already exist on
-- the WriFe Platform), these policies have already been applied
-- to the platform Supabase project (gzmgjkbtsvezfclmreru).
--
-- Running this file would error with "policy already exists".
-- Do not run it.
-- ============================================================
